var SampleData = [
{ "Id": "210", "Name": "Name 1", "Category": "Permanent", "Project": "Logistics", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "12000" },
{ "Id": "187", "Name": "Name 2", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 3", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SSE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 4", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 5", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 6", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 7", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 8", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 9", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 10", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 11", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 12", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Development", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 13", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 14", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 15", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 16", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 17", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 18", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 19", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 20", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 21", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 22", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 23", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 24", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 25", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 26", "Category": "Permanent", "Project": "Logistics", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 27", "Category": "Permanent", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "SSE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 28", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 29", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 30", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 31", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 32", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 33", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 34", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 35", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 36", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 37", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 38", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 39", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 40", "Category": "Permanent", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 41", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "Lead", "Salary": "16000" },
{ "Id": "187", "Name": "Name 42", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 43", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 44", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 45", "Category": "Temporary", "Project": "Logistics", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 46", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 47", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "Lead", "Salary": "12000" },
{ "Id": "181", "Name": "Name 48", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 49", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Development", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 50", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },


{ "Id": "210", "Name": "Name 51", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SSE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 52", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 53", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 54", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 55", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 56", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 57", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 58", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 59", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 60", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 61", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 62", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 63", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 64", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 65", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SSE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 66", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 67", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 68", "Category": "Temporary", "Project": "Logistics", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 69", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 70", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 71", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 72", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "Lead", "Salary": "13000" },
{ "Id": "186", "Name": "Name 73", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 74", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 75", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 76", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 77", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 78", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 79", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 80", "Category": "Permanent", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 81", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 82", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 83", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 84", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 85", "Category": "Temporary", "Project": "Logistics", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 86", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 87", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "Lead", "Salary": "12000" },
{ "Id": "181", "Name": "Name 88", "Category": "Temporary", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 89", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Development", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 90", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 91", "Category": "Permanent", "Project": "Logistics", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 92", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "Lead", "Salary": "13000" },
{ "Id": "186", "Name": "Name 93", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 94", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 95", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 96", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 97", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 98", "Category": "Permanent", "Project": "Logistics", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 99", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 100", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 101", "Category": "Permanent", "Project": "Logistics", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 102", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "Lead", "Salary": "13000" },
{ "Id": "186", "Name": "Name 103", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 104", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 105", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 106", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 107", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 108", "Category": "Temporary", "Project": "Logistics", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 109", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 110", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },


{ "Id": "210", "Name": "Name 111", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SSE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 112", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "13000" },
{ "Id": "186", "Name": "Name 113", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 114", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 115", "Category": "Permanent", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 116", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 117", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 118", "Category": "Temporary", "Project": "Logistics", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 119", "Category": "Temporary", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 120", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },

{ "Id": "210", "Name": "Name 121", "Category": "Permanent", "Project": "Logistics", "City": "Chennai", "Department": "Development", "Designation": "SE", "Salary": "16000" },
{ "Id": "187", "Name": "Name 122", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Testing", "Designation": "Lead", "Salary": "13000" },
{ "Id": "186", "Name": "Name 123", "Category": "Permanent", "Project": "HRMS", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "185", "Name": "Name 124", "Category": "Permanent", "Project": "HRMS", "City": "Bangalore", "Department": "Development", "Designation": "Lead", "Salary": "18000" },
{ "Id": "184", "Name": "Name 125", "Category": "Temporary", "Project": "HRMS", "City": "Mumbai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "183", "Name": "Name 126", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Development", "Designation": "SSE", "Salary": "14000" },
{ "Id": "182", "Name": "Name 127", "Category": "Permanent", "Project": "Banking", "City": "Chennai", "Department": "Testing", "Designation": "SE", "Salary": "12000" },
{ "Id": "181", "Name": "Name 128", "Category": "Temporary", "Project": "Logistics", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "15000" },
{ "Id": "180", "Name": "Name 129", "Category": "Permanent", "Project": "Banking", "City": "Mumbai", "Department": "Testing", "Designation": "Lead", "Salary": "17000" },
{ "Id": "178", "Name": "Name 130", "Category": "Temporary", "Project": "Banking", "City": "Bangalore", "Department": "Development", "Designation": "SSE", "Salary": "13000" },


];  